version: "3.8"
services:
  db:
    image: library/postgres:13.1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: konstantin01/foodgram-project:v1.1
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - ./static:/code/static
      - ./media:/code/media

  nginx:
    restart: always
    image: library/nginx:1.18
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d  
      - ./static:/code/static
      - ./media:/code/media
    depends_on:
      - web

volumes:
  postgres_data: