# Generated by Django 3.1.3 on 2020-12-18 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20201212_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoplist',
            name='used',
        ),
    ]
