# Generated by Django 3.1.3 on 2020-12-18 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_remove_shoplist_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoplist',
            name='created',
        ),
    ]
